### ISSUE TITLE
[Alerter] Rate limit requests to orderbook API

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/services#1017]
We are getting rate-limited from our alerter pod because we are fetching orders from our API too frequently. We should rate this call here:

https://github.com/cowprotocol/services/blob/a0832fd9644db6eae6bdab4eecb4e4b04d07e3bd/crates/alerter/src/main.rs#L65-L74

**Comment by nlordell** [comment]
Sounds like a bug in the alerter pod TBH. We should only fetch those for orders that were in the previous auction, but not in the next one. So the list of orders we need to fetch should be quite small...

Might be related to the recent refactor in #1015

**Comment by nlordell** [comment]
I added additional log message to double check there was no newly introduced issue in #1018. I random sampled an order from running locally (`0x6cffadbc...`), and it was missing from the auction because:
```
filtered order order=0x6cffadbc2a909cde15c4fd042ba667620b616a8ead0ed4488f0f567d16c855890c5fa5fa51d84227bfacdc56b36329286b37d051649602e4 reason=missing_price
```

So, it looks like these "bursts" of orders are happening because some orders are getting filtered out of the auction.

**Comment by nlordell** [comment]
This looks to have exacerbated the price estimation issues with Quasimodo+SCIP.
