### ISSUE TITLE
Introduce hard deadline for price estimates in the `autopilot`

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#1053]
The native price cache and limit order quoting in the `autopilot` is very sensitive to individual price estimators slowing down the process.
This can lead to a majority of limit orders not being quoted because of a single slow price estimator [[0](https://cowservices.slack.com/archives/C0361CDD1FZ/p1673473223246509)].
We already have some rate limiting logic in place but that doesn't work great in this case. Instead it makes sense to introduce another CLI argument for the `autopilot` that configures a hard timeout after which slow price estimation request get cancelled.

This would make the limit order quoting process very predictable which also helps with tuning other parameters. Ideally we would also get some metrics to count how many requests got aborted for each price estimator. This would allow us to create an alert based on those metrics so we can look into the poor performance in a timely manner.

**Comment by vkgnosis** [comment]
There is already a hard deadline for price estimates in the http request timeout. This might not be fine grained enough.

> This can lead to a majority of limit orders not being quoted because of a single slow price estimator.

True but it feels intrinsic with the way we have currently defined what a price estimate is. In the autopilot to get a price estimate we need to evaluate *all* price estimators to use the best result. This is problematic because as we have observed a single slow estimator makes every request slow. By using a deadline (as we already do through the http timeout), what we are really doing is softening this requirement so that we no longer require all price estimators. If that is what we want, we should do it more explicitly and configure the RacingCompetitionEstimator abstraction to require some subset amount rather than all.

**Comment by vkgnosis** [comment]
Made a writeup of some thoughts related to this here https://github.com/cowprotocol/services/issues/1055 .

**Comment by MartinquaXD** [comment]
> ... what we are really doing is softening this requirement so that we no longer require all price estimators. If that is what we want, we should do it more explicitly

This makes sense to me.

> configure the RacingCompetitionEstimator abstraction to require some subset amount rather

I think putting the timing requirement into the `RacingCompetitionEstimator` might make things a bit weird. For example what happens if we get the `n` estimates required by the `RacingCompetitionEstimator` to return early but there is still plenty of time left? Should we return early or wait for more prices?
In the first case we could get suboptimal prices.
In the second case a new flavor like a `TimedCompetitionEstimator` which only concerns itself with time could make more sense (the current implementation is already quite complicated).
