### ISSUE TITLE
Move token info fetching from Autopilot to Driver

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#1195]
I don't think this is necessarily part of the auction. To me, token metadata is "side-car" data (much like liquidity) which the driver "augments" before sending to the solver engine.

_Originally posted by @nlordell in https://github.com/cowprotocol/services/pull/1187#discussion_r1101428237_

**Comment by MartinquaXD** [comment]
Moving to verified quotes board since info fetching is currently only used for balancer liquidity fetching, which is only used in the autopilot / api because we still use built in price estimators. This will go away when verified quotes are fully deployed and we can finally start cleaning up properly.
