### ISSUE TITLE
Networking Errors Take Too Long to Timeout

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1237]
Last week, we ran into issues where calls for a certain external price estimator (0x specifically in this case) were failing on `reqwest::RequestBuilder::send`. From my investigations, this seems to be caused by TCP/networking related issues (we don't actually log the original `reqwest::Error`, so its hard to say, but from quickly browsing the code there isn't much else it could be).

```
2023-02-14T12:59:42.036Z DEBUG request{id="4dfc42eae8117c8834d1edc115c5e8f7"}: shared::order_quoting: calculating quote request=OrderQuoteRequest { ... }
...
2023-02-14T12:59:52.038Z DEBUG request{id="4dfc42eae8117c8834d1edc115c5e8f7"}: shared::price_estimation::competition: new price estimate query=Query { ... } result=Err(Other(Failed on send)) estimator="ZeroEx"
```

In fact, it looks like this is hitting the HTTP timeout of 10 seconds for just sending the request.

Ideally, we would be able to have separate timeouts for sending the request (and receiving the TCP ACK that the request was received), and waiting for a response, allowing us to error out earlier when facing networking issues.

**Comment by vkgnosis** [comment]
> Ideally, we would be able to have separate timeouts for sending the request (and receiving the TCP ACK that the request was received), and waiting for a response, allowing us to error out earlier when facing networking issues.

To be clear, you want a shorter time out for the `.send` call?
In reqwest `.send()` completing means the server gave a proper HTTP response but we didn't read the body from the connection yet. That's why after `.send()` the status code is already available. It is split into a separate body function for requests where the response has a large body. I don't don't think it makes sense to have a separate timeout for `send`. For most requests it makes sense to have a timeout for the whole process, including getting the body. From the top of my head I don't know how exactly the pre-configured timeout applies.
