### ISSUE TITLE
Special Treatment for CoW Reference Prices

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1238]
Since CoW reference prices are important for solver rewards computation, we should have some special treatment for them. Specifically, when building the solvable orders, we should use the last known CoW reference price instead of "pausing" the protocol.

**Comment by vkgnosis** [comment]
What do you mean by "pausing the protocol"? I think you mean that because we need the cow price for building the auction, so if we don't have it we can't create any auction. For this reason we should have special logic for the cow price (compared to the other price estimates) to ensure it is always available.
