### ISSUE TITLE
Send All Partially Fillable Limit Orders To Solvers

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1378]
https://github.com/cowprotocol/services/issues/1290#issuecomment-1484755755

Specifically, we currently filter out partially fillable limit orders in the same way we filter out market orders in the auction. That is, the `autopilot` heuristically decides which orders the users have balance for, and only send orders for which users have enough balance to execute the rest of the order.

This is not ideal because:
- If a user has X balance and 3 orders selling X, it isn't clear to the autopilot which is the "best" order to include in the auction, this is the job of the solvers
- If a user has X balance and a partially fillable limit order selling 2X, then it would be possible for half of the order to be matched, but it is currently being disregarded

The proposed change is to:
- [ ] include **all** partially fillable limit orders for which the user has some balance in the auction
- [ ] fetch user balances for partially fillable limit orders to send to the solver engines
- [ ] make sure that Gnosis solvers handle user balances

Related to https://github.com/cowprotocol/services/issues/1064, scoped specifically for partially fillable limit orders.

**Comment by vkgnosis** [comment]
The current description doesn't specify this, but this would make sense for all orders, not just partially fillable orders. Long term we should do it this way for all orders. Short term it is simpler to only have the new behavior for partially fillable orders.

What should we do?

**Comment by nlordell** [comment]
> What should we do?

Yes. However, this issue in particular is **only** for partially fillable limit orders. Eventually we want to do this for all orders, but it is a slightly larger change that solvers need to be aware of.

**Comment by vkgnosis** [comment]
Related https://github.com/cowprotocol/services/issues/1408

**Comment by vkgnosis** [comment]
Quick summary. In https://github.com/cowprotocol/services/pull/1406 we added a simpler version of this change to the non-colocation code. I'm hoping we implement the complete version only for colocation to save time.

Also, After trying to implement it, I feel this change does not became significantly simpler to implement only for partially fillable orders. We should implement it for all order types at the same time. It is unlikely that external solvers will quickly change their code to take balances into account so for some time we are going to need to make this choice for them with a similar algorithm as what we're doing now.

**Comment by vkgnosis** [comment]
Another summary. The current state is that autopilot only filters orders on individual settlability, which is enough sell token balance for sell amount + fee for FOK, and at least 1 balance for partially fillable. The driver does the full balance assignment.

The plan is to move this check (that already moved from autopilot to driver) into the solvers. We will do this only for partially fillable orders first, because solvers expect it for them already, while they don't expect it for FOK orders. We should create a per solver configuration flag that specifies whether the driver should do the balance assignment or whether the solver can handle it internally. The flag is useful in case a solver has not implement this correctly so that they don't produce invalid settlements. After we do this for partially fillable orders we extend the flag with another setting for all orders.

**Comment by MartinquaXD** [comment]
Initially solvers claimed they would like to manage partially fillable order prioritization themselves but then nobody ended up implementing it. I think for now we can keep the status quo (driver implements basic order prio algorighm)
