### ISSUE TITLE
Fee scaling for partial fills

### ISSUE THREAD

**Issue by fhenneke** [cowprotocol/services#1409]
It looks as if fees for partially fillable orders are not computed correctly from the settlement.

The test transaction [here](https://goerli.etherscan.io/tx/0xbd4734d2c727582cf162ee59202d7e75d3fc9d3c99a7c249cd81ac768f94651f) seemed to charge a fee of around 0.027ETH, while the [competition endpoint](https://barn.api.cow.fi/goerli/api/v1/solver_competition/by_tx_hash/0xbd4734d2c727582cf162ee59202d7e75d3fc9d3c99a7c249cd81ac768f94651f) reports a fee of 0.013ETH, i.e., around 50% of the actual fee.

I am not sure if this is a bug or of it still persists.

One potential cause might be the scaling applied to the fee in this function:

https://github.com/cowprotocol/services/blob/7f664e81020bf3e46558cdfb8b923a0170d41cef/crates/autopilot/src/decoded_settlement.rs#L258

**Comment by nlordell** [comment]
AFAICT, this was fixed in https://github.com/cowprotocol/services/pull/1411 and we no longer scale partially fillable order executed fee amounts (instead they get recorded in the DB with the scaled signed `fee_amount` + the unscaled `surplus_fee_amount`).

We should probably confirm that this is indeed fixed before closing the issue.
