### ISSUE TITLE
`driver` tracing and metrics

### ISSUE THREAD

**Issue by cowfee** [cowprotocol/services#1475]
The driver needs to expose some metrics and tracing for observability. There's already some logging, but this should probably be more structured.

#### Requirements

- Log every auction.
- Log all solutions returned from the solver engines.
- Whenever a solution is dropped, log the solution ID and the reason why it was dropped.
- Log the winning solution.
- Log when solutions are successfully merged.
- Log as much as possible in `infra::mempool` and `boundary::mempool`. This can be modeled after the logging in the legacy codebase, to understand what's useful to log and what isn't.
- Metric for the number of solutions submitted to the protocol.
- Metric for the number of winning solutions.
- Solution failure metric labeled by failure reason, to track how often solutions are being dropped and why.

These are the fundamental requirements to be able to go into production. They will be refined over time. Some additional nice-to-haves would be metrics related to solution merging.

Note that some logging and metrics are already inherited from the legacy code by virtue of the boundary modules.

#### DDD

I imagine a module in `infra` which exposes hooks which are meaningful to the domain. For example, something like `struct infra::observe::AuctionSolved(auction::Id, Solution)` or `infra::observe::auction_solved(auction::Id, Solution)` or similar.

**Comment by nlordell** [comment]
I think we should add metrics around transaction submission as well. I think we inherit a bunch from using the `boundary` module, but it might make sense to have more metrics for the driver-specific logic there as well.

Generally speaking, transaction submission is an area where you want to err on the side of "too much logging/metrics" rather than too few (given that many issues appear in weird, not easily reproducible, race-condition-y ways because of the decentralised nature of the blockchain).

**Comment by nlordell** [comment]
Other than that, things look good. Note that we inherit metrics and logging from liquidity indexing.
