### ISSUE TITLE
Don't rely on legacy code for solution merging in `driver`

### ISSUE THREAD

**Issue by cowfee** [cowprotocol/services#1478]
Ideally the `Settlement` type and all of the code related to it should be in the `driver`. This includes the code for merging settlements. The legacy code is [here](https://github.com/cowprotocol/services/blob/753eccd64befe24c44103cf58b39bb47df529f67/crates/solver/src/settlement/settlement_encoder.rs#L628-L696) for reference. Below is a description:

The clearing prices between two solutions A and B should be merged as follows:
- For those tokens which have clearing prices in both A and B, all of the clearing prices in A can be scaled (using the same factor) to give the clearing prices in B (and, of course, vice versa). Meaning, the common clearing prices are equal up to a scaling factor. If this is not the case, the solutions cannot be merged.
- If there is a clearing price in A which isn't in B (or vice versa), then simply use that clearing price in the resulting merged clearing prices set without modification.

The `tokens` field should be removed as business rules should define it to be equal to the tokens in clearing prices.

The `trades` and `unwraps` should be merged as a set union. If `trades` are not disjoint (i.e., the two solutions solve some of the same orders), then the two solutions can't be merged, because it's impossible to know how to merge the onchain interactions correctly.

The idea of merging clearing prices seems (at first glance) to represent an important piece of domain logic.

It's important to note that once the merging code moves into the driver, the merging should be done on the `Solution` type. It's currently done on the `Settlement` type because of the boundary integration.

**Comment by cowfee** [comment]
What's the deal with merging `trades`? In the legacy code, if the settlements being merged have any orders in common, they are considered to be unmergable. This seems incorrect to me. At least, if the trades have the same interactions, the settlements should be mergable? Or is this a minute detail not worth bothering with?

**Comment by MartinquaXD** [comment]
> At least, if the trades have the same interactions, the settlements should be mergable? Or is this a minute detail not worth bothering with?

It's not always given that you know which custom interactions belong to which settlement. Imagine 2 orders that both sell token A for token B. We could have a solution which has 1 interaction per order getting the liquidity from some pool but we could also have a solution that only does a single interaction which acquired enough liquidity for both trades.
This can complicate things.

And a more specific reason why this merging currently doesn't happen in the legacy code is that it only merges solutions of single order solvers (`1Inch, `0x`, ...) meaning that 2 solutions that settle the same order with the same interactions are identical because they can not differ in the execution of another order because only a single order will ever be part of those solutions.
