### ISSUE TITLE
Re-Evaluate choice of MAX_REORG_BLOCK_COUNT

### ISSUE THREAD

**Issue by bh2smith** [cowprotocol/services#1492]
https://github.com/cowprotocol/services/blob/042aac25dbb2219b4498142738cb87e3ddca7b45/crates/shared/src/event_handling.rs#L21

According to [this article](https://decrypt.co/101390/ethereum-beacon-chain-blockchain-reorg) the deepest reorg (occurring last year) was 7 blocks. It would be nice to concretely investigate the deepest ever reorg along with frequencies to see if this value can be reduced. 

Such a change might also improve processing times and save on RPC calls (if the services are frequently truncating and repopulating this far back).

**Comment by vkgnosis** [comment]
We should compare advantages and disadvantages of this approach.

When you mention saving RPC calls, you mean the event updating. We won't save RPC calls there because we already detect how big a reorg is and only update that much (right, iirc Dusan implemented this).

The motivation from your side is having the auction_id to tx_hash association available more quickly. This also effects the solver_competition by tx_hash endpoint. The delay for this process uses the same constant.

**Comment by vkgnosis** [comment]
It might be possible to have the auction id to tx hash available immediately. It would then still be open to change due to reorgs but that can be up to the user of the API to handle. If they want to trust it after 10 blocks they can. I haven't looked into how I'd implement this, just brainstorming.

**Comment by bh2smith** [comment]
I would actually prefer to be guaranteed of the link and keep reorg handling as low level as possible. I was hoping to do some research on deepest reorg ever which I have heard is only ~7 blocks... and I would be comfortable with something in the range of 10 - 15. Assuming that anything deeper might imply the entire network is permanently compromised.

**Comment by MartinquaXD** [comment]
According to this [page](https://hackmd.io/@prysmaticlabs/finality#How-Finality-Works-in-ETH2) finality is not as straight forward as our constant suggests. Since we are already not strictly correct about our model of finality we might as well consider lowering the threshold since our approximation already worked well enough and even seems a bit too pessimistic in practice.

**Comment by bh2smith** [comment]
This very article suggests approximately what we have here (2 epochs of 32 blocks each)

> Unless major validators go offline, or if there is a serious bug in a popular client implementation, the incentive to always finalize the current_epoch - 2. Given epochs in eth2 are 6.4 minutes long, the epoch 12.8 minutes ago should always be finalized in ideal conditions.

Just a bit below ([here](https://hackmd.io/@prysmaticlabs/finality#Incentives-and-reorgs))
