### ISSUE TITLE
Drop duplicated `wrapAll` interactions of EthFlow orders

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#1496]
Every EthFlow order has a pre-interaction that wraps all ETH the ethflow contract holds so it can be used to trade in a settlement. This only has to happen at most once per settlement so in a settlement that settles 2 or more EthFlow orders at once we omitted duplicated `wrapAll()` interactions.
However, this clashed a bit with implementing general pre- and post-interactions without introducing convoluted exceptions in the code so we dropped it for now in #1485.
If this [research request](https://cowservices.slack.com/archives/C0361CCTFD5/p1683786242644879) shows that we would miss out on a lot of gas savings it would make sense to reintroduce this optimization, though.

**Comment by nlordell** [comment]
I [simulated](https://dashboard.tenderly.co/public/safe/safe-apps/simulator/7191180c-92d2-424c-b6b0-d9a85f45c655) the settlement at transaction []() with an extra `wrapAll` call and it added exactly 6300 gas to the transaction.

With dune, I estimated that it has saved us ~3.3M gas units since the launch of EthFlow. At the current gas price, that would roughly 0.25Ξ. With that in mind, I don't think this regression costs us a lot in absolute terms.

<details><summary>query</summary>

```sql
with multis as (
    select
      evt_tx_hash, count(*) as num_orders, (count(*) - 1) as extra
    from gnosis_protocol_v2_ethereum.GPv2Settlement_evt_Trade
    where owner = 0x40a50cf069e992aa4536211b23f286ef88752187 or owner = 0xD02De8Da0B71E1B59489794F423FaBBa2AdC4d93
    group by evt_tx_hash
    having count(*) > 1
)
select sum(extra) * 6300 from multis;
```

</details>
