### ISSUE TITLE
Add deadline for solution merging in the `driver`

### ISSUE THREAD

**Issue by cowfee** [cowprotocol/services#1498]
Merging solutions is an optimization. The driver shouldn't keep merging until there's no more solutions that can be merged together; instead, it should stop prematurely if it exceeds some deadline. The deadline can be hardcoded to begin with, and calculated based on config once https://github.com/cowprotocol/services/issues/1474 is implemented.

**Comment by sunce86** [comment]
Merging is done [here](https://github.com/cowprotocol/services/blob/main/crates/driver/src/domain/competition/mod.rs#L108) and AFAIS there is no deadline. 
Not blocking prod colocation i'd say.

**Comment by fleupold** [comment]
This may be an issue if we merge many settlements, since we simulate each new settlement [here](https://github.com/cowprotocol/services/blob/a44ea21090dd4b22ebd4ae0f274abcc5984d21ad/crates/driver/src/domain/competition/solution/settlement.rs#L300).

Simple solution would be to not do another iteration of merge if the deadline is close.

Better solution would be have `solve` return a stream and have the outside caller return whatever the stream has produced when the deadline gets close. Leave merging unlimited then.

Middle ground may be to store the "currently best candidate" in the competition and have the caller return this when the deadline gets close.

**Comment by fleupold** [comment]
This is causing issue in Gnosis Chain in prod and was likely also the reason we saw a lot of timeouts in our last mainnet testing session. @MartinquaXD mentioned that @sunce86 had a proposal on how to address this?

Here are some example logs showing the driver receives a solution from the oneinch solver but still times out (likely because all the async work in https://github.com/cowprotocol/services/blob/c70090e31af0a90e4c481dd3dd3cc93a1c6a3919/crates/driver/src/domain/competition/mod.rs#L81): https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/r/s/mA2rl

**Comment by MartinquaXD** [comment]
@fleupold https://github.com/cowprotocol/services/pull/2040 is the PR that implemented a fix for a similar problem for the baseline solver.
I think using a channel to report back solutions should work well enough and does not introduce the annoyances of working with streams.
