### ISSUE TITLE
Store Winning Quote Source in Database

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1583]
This issue captures the work of storing the quoter's solver address in the database in the `order_quotes` table.

Specifically, under [this proposal](https://forum.cow.fi/t/cip-draft-incentives-mechanism-for-the-price-estimation-competition/1718) we plan on implementing rewards for quoting orders. For this to work, we need to tie each order

This issue captures the work to:
1. Extend the `quotes` database with a `solver` address (the solver's submission address).
2. Include the `solver` in the `order_quotes` table that are tied to orders.

**Comment by MartinquaXD** [comment]
Just wanted to point out that we continually update the `surplus_fee` of fok limit orders. That means we could do an unlimited number of quote requests but can only store a single `solver_address` because we only have a single `order_quote`.
Another consideration is that there are lots of duplicated fok limit orders so we went with the approach of doing 1 quote to update all identical orders.
@harisang, @bh2smith how big of an issue would these points be for your analysis

**Comment by bh2smith** [comment]
I would have initially expected to have a single quote linked to a single order, but in the event of an order being touched multiple times by different quotes it seems more like we want to link quotes to trades (which is also fine by me). Note that we are, from what I recall, only rewarding quotes for market orders, although I guess there are "Fill or Kill" (aka FoK) market orders. 

I don't have a preference here as long as what we wind up with is something coherent.

**Comment by nlordell** [comment]
@MartinquaXD - I talked with @harisang and at first, we would only be considering quotes for market orders. With that in mind, the restriction for the FoK limit orders would not be a big issue.

In the medium term, we expect FoK limit orders to also have their fees computed solver-side, which means that this would no longer become a problem.

**Comment by sunce86** [comment]
Closed with https://github.com/cowprotocol/services/pull/1637
