### ISSUE TITLE
Store `is_liquidity_order` in the database

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#176]
Currently detecting liquidity orders placed through our API happens by looking up the owner of the order in an allow-list of private market makers.
This list can be configured with `--liquidity-order-owners addr1,addr2,addr3`.
If the owner of an order is currently in that list it gets treated as a liquidity order regardless of whether it was a liquidity order when we it got stored in the database.

The proper approach would be to decide whether an order is a liquidity order before storing it in the database and storing that information along with it. That would prevent an order changing its type after reconfiguring and restarting the service.

I think there are 2 ways this could be implemented:
1. Keep most things as they are right now and add the field `is_liquidity_order` to `OrderMetadata` before storing it in the DB.
2. Add `is_liquidity_order` to `OrderCreation`. This would allow users to decide whether they want a liquidity order or a normal order. It would still make sense to lock that feature behind an allow-list, though. To not break compatibilty of the `/create_order` endpoint the field `is_liquidity_order` could be optional with `false` as the default.

**Comment by MartinquaXD** [comment]
I would be for option 2 but I guess there was a reason initially designing the system such that people can't decide?

**Comment by vkgnosis** [comment]
I feel that first we have to formalize what we mean by "liquidity order" and what problem they solve. Something like

> Liquidity orders are functionally the same as normal smart contract orders but are not placed with the intent of getting actively getting traded. Instead they facilitate the trade of normal orders by allowing them to be matched against liquidity orders which uses less gas and can have better prices than external liquidity.
As such liquidity orders will only be used in order to improve settlement of normal orders. They should not be expected to be traded otherwise and should not expect to get surplus. Liquidity orders are usually partially fillable orders.

With that in mind to me it makes sense to allow the person placing the order to decide whether they want to create a liquidity order. If you have access to an account that can place liquidity orders then you can already also place non liquidity orders by using a different account and there is no reason for this restriction.

OrderCreation is tied very specifically to the smart contract. It contains all the information necessary for orders on a smart contract level and all the information is part of what is signed by the owner account and verified by the contract.  (We should document this.) So it does not make sense to store this field there, it should go into OrderMetadata.

In the api we can still allow the user to specify this when they post and order to us but it shouldn't be part of this struct. Like I said I think this makes sense but it also isn't particularly important or urgent so I would implement the basic functionality first.

**Comment by MartinquaXD** [comment]
> it should go into OrderMetadata

I wasn't aware that `OrderCreation` was tied to the smart contract. In that case putting it in the `OrderMetadata` definitely makes more sense. 👍 

Your definition is very detailed and is in line with what I associate with a liquidity order. Should we maybe also mention `market making` somehow? I believe this term communicates very well the idea of a liquidity order while being more widely known (although some people might expect to earn fees for being a market maker).
