### ISSUE TITLE
Make solvers vector optional in solver crate

### ISSUE THREAD

**Issue by devanoneth** [cowprotocol/services#1791]
Currently it is not possible to run the solver / old driver against only an external solver. Trying to pass an empty vector of some kind to the `--solvers` flag in the `solver` crate causes an error. Previously, it was possible to instruct the old driver to run against only the `CowDexAg` solver and have an external solver accept those requests. This was removed in #1743.

If you agree, I'm happy to open a PR to make the `solvers` vector in the `Arguments` struct an `Option` and allow it to be `None` iff at least one external solver is set.

**Comment by MartinquaXD** [comment]
Totally on-board with that. I even opened an issue about it but never found the time to implement it. 🙈 
FYI just turning the argument to `Option` doesn't really work with vectors. See this [discussion](https://github.com/cowprotocol/services/pull/1181#discussion_r1098607619) for more context.

**Comment by devanoneth** [comment]
> A decent workaround for now is to use `--solvers Baseline --baseline-sources None`. It will run the baseline solver, but without liquidity, so it can never participate.

Thanks for this!

> Note that we plan on `rm -r` the `solver` crate with co-location.

I did notice it's called `old_driver` in some parts of the code so that makes sense. Is there another crate that I should be running then for e2e tests to POST the auction to our solver's `/solve` endpoint? Or is that still the `solver` crate for now?

**Comment by MartinquaXD** [comment]
> Is there another crate that I should be running then for e2e tests to POST the auction to our solver's /solve endpoint? Or is that still the solver crate for now?

This will be the way to go until we deploy colocated drivers which is hopefully soon ™️ . You can already future proof your tests by following the setup of tests such as `e2e/tests/e2e/colocation_univ2`.
These `colocation` tests already spin up processes as we would when we deploy colocated drivers.
Instead of having a `solver` process that sends requests to your solver endpoint directly these tests spawn a `driver` that sends requests to a `solvers` process. In your case you would have to add another indirection because existing solvers are not yet compliant to the new format we are working on.
To run an existing solver in the colocated setup you would have: `driver` that sends requests to a `solvers` process (run with `legacy` mode`) that sends requests to an existing solver.
In this case `solvers legacy` is only a slim wrapper that turns the new format into the format the current solvers understand. Hope this helps.
