### ISSUE TITLE
Refactor `solvers` Configuration

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1853]
> Strictly speaking the solver in `domain` should not use a config type from `infra`, right?
> Seems like `Baseline` should define what kind of configuration it expects and the `infra` module should return that.

_Originally posted by @MartinquaXD in https://github.com/cowprotocol/services/pull/1852#discussion_r1319791849_

Specifically, this dependency:

https://github.com/cowprotocol/services/blob/6bfd873f77f1924137c1507bc793f1992cca575b/crates/solvers/src/domain/solver/baseline.rs#L19

as well as this dependency:

https://github.com/cowprotocol/services/blob/6bfd873f77f1924137c1507bc793f1992cca575b/crates/solvers/src/domain/solver/naive.rs#L12-L13

Should be removed in favor of a domain specific config struct like

https://github.com/cowprotocol/services/blob/6bfd873f77f1924137c1507bc793f1992cca575b/crates/solvers/src/domain/solver/legacy.rs#L16-L23

**Comment by Braqzen** [comment]
First time poking around so I'm completely ignorant.

The `legacy` config is unlike the `baseline` and `naive` structs.

Is the intention to 
1) entirely move the `baseline` and `naive` structs into the `solver` alongside `legacy` (move some files around and change the import to be from `domain` instead)
2) merge those structs into the `legacy` config struct so that there is 1 large `domain` config, delete the infra config structs and use the newly merged struct
3) merge the `baseline` and `naive` structs into a new struct alongside the `legacy` struct inside the `solver` module, leaving the legacy config untouched
4) something else?

**Comment by fleupold** [comment]
Hi @Braqzen, thanks for taking a look! 

We are trying to follow the Domain-driven design pattern in the codebase. Currently the domain is using types from the infra module which is a violation of DDD principles.

The goal of this task is to remove the `infra::config::baseline::Config` dependency inside the `domain::solver::baseline` module (and `naive`). It looks like `domain::solver::legacy` already defines its own config. I think we should do the same for baseline/naive. It's then questionable if the existing `Config` struct inside `infra` still needs to exist or if [`load`](https://github.com/cowprotocol/services/blob/cf33f6f83f6079af8cb39a8884cbbad9cf225dc2/crates/solvers/src/infra/config/baseline/file.rs#L51) can directly return the domain type (this seems to be the case for legacy, so I think it's fine).

**Comment by fleupold** [comment]
Thank you @Braqzen for your contribution. Please let us know (either here or in DMs) the address, you'd like to receive your reward on.
