### ISSUE TITLE
Gnosis solvers are currently submitting multiple identical solutions

### ISSUE THREAD

**Issue by harisang** [cowprotocol/services#1869]
It seems that Gnosis solvers are submitting multiple identical solutions in both prod/staging and in both mainnet/Gnosis Chain. This doesn't really affect the auctions themselves, but it would be good to investigate why it is happening and whether this causes duplicate API calls.

Relevant slack discussion here:
https://cowservices.slack.com/archives/C0361CDD1FZ/p1694429913178019

**Comment by sunce86** [comment]
If we take auction `8819222` as an [example](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/r/s/X5puv), there are 6 1Inch solutions, and the orders uids in those solutions are: 

1. `0x2c5216af42d0491a7411f019eeed282fceb7bfaa9236e9fd008e862acc788402ffab14b181409170378471b13ff2bff5be012c6465248b6c`
2. `0x1b4804444ceaf9b6d9b4e9bd5513b04ff1696560f412fa616ee1035c91bc854e212ac2a9d605bd50a6b7c8770b8a542f5590074564ff3fad`
3. `0x7c581aa7fb209f6023d8b2a0721b502660f6b9980001eea34e018721c65425c7ffab14b181409170378471b13ff2bff5be012c6465248b69`
4. `0x9acd65ffc957d5ada66c585e17f2b9cb52ea918779a598ef3e151e43cc039007ffab14b181409170378471b13ff2bff5be012c6465248b73`
5. `0x121719443b1f8ddd5ec448f8c0a8bf9cbdab708febc72e30401f7933e0fa7706ffab14b181409170378471b13ff2bff5be012c6465248b72`
6. `0x1b4804444ceaf9b6d9b4e9bd5513b04ff1696560f412fa616ee1035c91bc854e212ac2a9d605bd50a6b7c8770b8a542f5590074564ff3fad
0x2c5216af42d0491a7411f019eeed282fceb7bfaa9236e9fd008e862acc788402ffab14b181409170378471b13ff2bff5be012c6465248b6c
0x121719443b1f8ddd5ec448f8c0a8bf9cbdab708febc72e30401f7933e0fa7706ffab14b181409170378471b13ff2bff5be012c6465248b72`

So, there are 5 settlements containing a single order and 1 merged settlement containing 3 orders. 
To me this is expected behavior. `SingleOrderSolver` should produce multiple solutions while ranking procedure should decide which one of them is the best.
Especially taking into consideration that we can control two parameters:
1. max number of settlements per solver
2. max number or merged settlements per solver.

**Comment by harisang** [comment]
I messed up reading the logs and I checked auctions with multiple identically looking (but not identical!!) orders. Things look fine after al. Thanks to  @sunce86 for investigating and clarifying things!
