### ISSUE TITLE
We still report a price estimation winner when all estimators fail

### ISSUE THREAD

**Issue by harisang** [cowprotocol/services#1870]
Not urgent, but I think we should fix the following.

Whenever all price estimators fail for a quote request, there is still a log emitted (see an example [here](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/doc/c0e240e0-d9b3-11ed-b0e6-e361adffce0b/cowlogs-prod-2023.09.13?id=q4syjooBQgsUfyaRMm1S)) that says there is a winning price estimate. Besides the log being misleading, does this mean that we somehow perceive at that part of the code that we indeed have a valid estimate? I don't think this implies any further bugs as we are probably catching this somewhere else, but it doesn't feel right.

**Comment by MartinquaXD** [comment]
Keeping this admittedly misleading log was a [deliberate decision](https://github.com/cowprotocol/services/pull/1769#issue-1853112936) to keep it simple to get the final result of a quote competition without having to grep for 2 different logs.
Due to the static type system the code does not assume that this is a valid response.
Unless you feel strongly that having 2 logs with slightly different wordings is an improvement I would like to close this issues and leave things like they currently are.

**Comment by harisang** [comment]
Oh i had missed that discussion. I don't have a strong opinion on this, just raised the issue because of the somewhat misleading log. But I agree this doesn't cause any real issues so I will go ahead and close it.
