### ISSUE TITLE
chore: Add metric for price estimates deviation

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#1921]
### Background
For a group of price estimates, add metric that shows the [standard score](https://en.wikipedia.org/wiki/Standard_score) of the winning solution.
Apparently, `CompetitionEstimator` would be a good place to add this metric.

Later on, we can add grafana alert and inspect if the standard score is too big which would indicate that the winning solution is far away from what the general truth is (what most other estimators return).

**Comment by acanidio-econ** [comment]
standard score (or z-score) are a common way to detect outliers whenever there are several observations from a poulation. For our purposes, suppose that "executable prices" for a token pair follow a normal distribution. If we have enough observation, we can compute a mean and standard deviation. We can then consider a specific price and ask: what is the probability that this specific price comes from the distribution of executable prices? If the answer is too low (10% or 5%), we may flag this price as suspicious, that is, not really being executable.

**Comment by acanidio-econ** [comment]
We can repeat the same simulation with 4 observations. Again, the lowest observation is 1. If the second lowest observation is 2, then the simulation results are ![4-obs-2](https://github.com/cowprotocol/services/assets/68323453/8732062e-7525-4a5f-8734-d1e9331c294e)
Hence, if z=1.2, then observations [1,2,2,3] or [1,2,3,4.5] would trigger an alert.

if the second lowest observation is 3, then the simulation results are
![4-obs-3](https://github.com/cowprotocol/services/assets/68323453/2073dbcc-0d36-463a-b0d0-26d1e6c8cc57)
Hence, if z=1.2, then observations [1,3,3,5] and [1,3,4,6] would trigger an alert.

if the second lowest observation is 4, then the simulation results are
![4-obs-4](https://github.com/cowprotocol/services/assets/68323453/23607327-76f0-404f-9706-ee8fec5162b8)
Hence, with z=1.2, observations [1,4,4,7] and [1,4,5,8] would trigger an alert

**Comment by acanidio-econ** [comment]
Anyway, the formula for the  standard deviation (using the unbiased estimator of the variance) is [here](https://en.wikipedia.org/wiki/Standard_deviation):
`s:=sqrt( ( (x1-xm)^2 + (x2-xm)^2 +...+ (xT-xm)^2 )/(T-1) ) `
where `T` is the number of observations and `xm` is the sample average. The z-score of a given observation is then 
`(xi-xm)/s`
We are interested in the max z-score. We could start from the rule of thumb of considering a max z-score of 1.2 as problematic.

**Comment by fleupold** [comment]
Do we still want to implement this suggestion in a world where we have verified quotes (ie we simulate the calldata a solver reports in their quote and only use a quote if the simulation matches the amount they claim)?

This would make it very unlikely for solvers to accidentally report unrealistic quotes (only if the e.g. underwrote private liquidity orders for it).

My main worry with this approach is that it will likely cost some significant engineering time to monitor and fine tune this system so that we are not accidentally ignoring good quotes (we have seen quotes where only two or three solvers respond with significant difference in the results, but all of them being valid).

It is true that verified quotes do not work until the user has actually connected their wallet (and the wallet has sufficient funds to make the trades they are quoting). Until then bogus estimates could still be returned. However, I'd argue that in those cases the user is unlikely to place an order anyway, so what's the value in showing them a realistic quote (I'd rather show them a message in the UI for unverified quotes that those are only indicative and might change once they connect a wallet with sufficient funds).

If at all, I'd like us to not filter out any quotes that have been verified no matter how good they are (to avoid false negatives in our detection). But in that case I wonder if this task is worth the cost of building it.
