### ISSUE TITLE
feat: Calculate executed protocol fees in postprocessing

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2112]
### Problem
`on_settlement_event_updater` runs for each settlement and calculates some data to be stored in database. Here, for each limit order, we should fetch fee policy and quote from database and calculate the executed protocol fees. Then, those fees need to be stored into `order_execution`.

**Comment by fleupold** [comment]
My point is why even differentiate between the two (at least on a database level). The user paid 10 USDC in fee, why do we want to differentiate between the surplus fee and the protocol fee (maybe there is an obvious reason, but I'd just like to challenge this assumption)

The protocol fee will in any case have to be computed from the order itself since some solvers may not charge it from the order in an on-chain observable way. Let's stick to the example above (and assume the user placed a limit order expecting 80 USDT outcome):
- Solver A uses our driver provided logic to charge fees. Thus they report a clearing price of 1 and an order specific price of 0.9 (adjusting $5 of network fee and $5 for protocol fee)
- Solver B uses their own driver. They report a clearing price of 0.9 and no order specific price

In both cases the protocol will request $5 - 50% of the difference of 80USDT and 90USDT -  from the solver as a protocol fee at the end of the week. This is assuming the solver computed fee [CIP](https://forum.cow.fi/t/cip-draft-solver-computed-fees-rank-by-surplus/2061/3?u=andreac) passes and solvers with heavy private market making arms implement their own driver.

How should the database records for both executions look like?

**Comment by sunce86** [comment]
> why do we want to differentiate between the surplus fee and the protocol fee

Probably for accounting reasons.

> Solver B uses their own driver. They report a clearing price of 0.9 and no order specific price

Need to adjust the example, so:

- Solver A uses our driver provided logic to charge fees. Thus they report a clearing price of 1 and an order specific price of 0.875 (adjusting $5 of network fee and $7.5 for protocol fee)
- Solver B uses their own driver. They report a clearing price of 0.875 and no order specific price

For second, based on the fact that we take 50% as protocol fee, we would see that the $87.5 - 80$ = $7.5 is 50% of the protocol fee, meaning the solver provided a solution for price of $95. The protocol fee would be $7.5 and the network fee would be unknown (0) - or calculated as gas cost from settlement?.

**Comment by fleupold** [comment]
> We as a protocol define the order of how the fees should be taken (first surplus, then protocol fees)

Surplus fee is not a requirement though (a solver can settle a batch with two orders without any visible surplus fee and still be profitable because they priced their cost into the exchange rate). In this case (solver B example), how would the table be populated? Would network fee be negative (given that surplus fee is 0 and protocol fee is $7.5 based on the observed price improvement)?

**Comment by harisang** [comment]
Had a quick read, and will revisit again.

A first comment, as I don't think we have consensus within the solver team.

> Solver B uses their own driver. They report a clearing price of 0.9 and no order specific price

Personally, I would like solvers to report the UCP and the per order clearing prices. Although not necessary I guess, I do see the value of getting essentially a price feed from solvers. E.g., say gas is high and a user for some reason is selling 100 USDC for DAI. Then it might be the case that 50 USDC is the gas. Having a solver just report p(DAI) = 1 and p(USDC)=0.5 is of course fine for the execution onchain, but it conceals information. One could look at the gas cost, but in a batch things become less clear. So what do these prices mean; do we have a depeg, do we have huge protocol fees, do we have high gas costs or any combo of these?

For this reason, I would propose that solvers must provide a UCP.

Regarding the discussion about how refined must be the distinction between different kinds of fees in the database, I will think about it and get back to you.

One thing to note (although i guess this is unrelated to the database) is that we would like to rank solutions before taking the protocol fee. I.e., in your example above, if the surplus the user receives is $7.5 and another $7.5 was the protocol fee, then the "rank by surplus" objective should assign a value of $15 to that solution; the rationale being that solvers try to maximize the size of the pie and should not care / treat differently orders with or without protocol fee.

**Comment by sunce86** [comment]
Closed as not needed. Decided to just provide the input for calculating the protocol fees.
