### ISSUE TITLE
chore: Investigate auction propagation delay between driver <> solver engine

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/services#2133]
### Background

Similar to #2095 there is another 1.7s propagation delay between the driver and the solver-enginer (cf. https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/r/s/U1XTl)

> 2023-12-07T08:38:34.078Z DEBUG request{id="17245"}:/solve:auction{id=8122282}: shared::http_solver: http solver instance name is 2023-12-07_08:38:34.078506830_UTC_Ethereum___Mainnet_1_8122282
2023-12-07T08:38:32.337Z DEBUG request{id="17245"}:/solve{solver=otex-solve auction_id=8122282}: driver::infra::api::routes::solve: auction task execution time elapsed=556.865172ms auction_id=8122282

It would be good to see if we can reduce this as well since we are leaking time the external solvers can actually spend on finding a solution.

**Comment by MartinquaXD** [comment]
There are only 2 async operations happening in the measured code path:
1. fetching current gas price
2. fetching token meta data (symbol, decimals, contract balance)

`2` is heavily cached but if we encounter a token that is not cached all solvers would send 3 RPC requests per uncached token. If this is the culprit we could use the `RequestSharing` component here to ensure they don't send duplicate requests.

**Comment by MartinquaXD** [comment]
Follow up on this. Each driver now spends 2-3 ms on this part most of the time.
But there can still be unfortunate timings when we see a new block right before the auction or even during the auction.
For example [here](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-13T08:55:29.019Z',to:'2023-12-13T08:55:34.317Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,key:kubernetes.labels.app_kubernetes_io%2Fcomponent,negate:!t,params:(query:controller),type:phrase),query:(match_phrase:(kubernetes.labels.app_kubernetes_io%2Fcomponent:controller))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,key:kubernetes.container_name,negate:!t,params:(query:mainnet-api-prod),type:phrase),query:(match_phrase:(kubernetes.container_name:mainnet-api-prod))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,key:kubernetes.labels.network,negate:!f,params:(query:mainnet),type:phrase),query:(match_phrase:(kubernetes.labels.network:mainnet)))),grid:(columns:('@timestamp':(width:164))),index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,interval:auto,query:(language:kuery,query:'mainnet%20and%20log:%20%228147027%22'),sort:!(!('@timestamp',desc)))) 1 driver was able to finish the task in 3ms and then all the subsequent drivers needed multiple 100ms because we saw a new block.
But I think there is nothing that can reasonably be done about this.
