### ISSUE TITLE
Proper support for `app_data`

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#218]
The idea of the `app_data` field is that it contains a hash of a file stored on IPFS. This file is supposed to be a JSON and can contain all sorts of information. This field has to be signed by the user so it can be used to store trusted information.
Right now we don't properly support reading the actual contents of the file on IPFS and only really know about the hash stored in the order.

Good support for that could enable us to quickly extend the order format when we want to add new data to the order which needs to be signed by the user.
In order to use the `app_data` ergonomically in the back end we need to be able to retrieve the associated file from IPFS and parse it.

### Useful Links
[design doc](https://docs.google.com/document/d/1byrhnRMWhrT_j45vXSpPprD2IBC2FGhpymNVBv-plMo/edit)
[tool](https://codepen.io/pacara/pen/BadZgjg) to decode data behind `app_data` hash
[app_data schema](https://github.com/cowprotocol/cow-sdk/blob/main/src/schemas/appData.schema.json)
currently used `app_data` [values](https://docs.google.com/spreadsheets/d/19Pq_5wKuZl669N3QuvhXSkaXur6KOrpSpAF0Rf8SWWc/edit#gid=0)
[IPFS docs](https://docs.ipfs.io/)

**Comment by anxolin** [comment]
I think AlexH reads and fetch this JSON so it can be used for the affiliate program. I would check with him how we does it, probably his logic can be reused

**Comment by fleupold** [comment]
Agree that reading the file from IPFS is a good way to start. Later, in order to avoid race conditions and simplify the UI logic, we could extend the quote and order endpoint to also include this json as a separate field. 
This way the frontend wouldn't have to maintain the upload logic and there wouldn't be the race of a new document being written to IPFS and shortly after being requested by the driver (before it may have propagated).

**Comment by anxolin** [comment]
> This way the frontend wouldn't have to maintain the upload logic and there wouldn't be the race of a new document being written to IPFS and shortly after being requested by the driver (before it may have propagated).

That would be nice indeed. Let us know if this changes, because now we are dealing with some "parallel" upload of the document. 

This will make also that not necessarily the document will be accesible right after we send the order. It might take a few seconds. We don't want to delay the order posting, or make it fragile in case the document upload fails. So, we send the order and upload the document in parallel. The document has some re-attempt logics in case of an error uploading.
