### ISSUE TITLE
Track which submission strategy mined a transaction

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#225]
Currently we only track successes/errors when a submission strategy tries to submit a transaction.
To improve our knowledge about the effectiveness of each strategy it would be good to know which by which network a transaction actually got mined.
To do that we most likely have to make sure that each strategy submits a transaction with a unique hash. This might be done by introducing a slight jitter in the gas parameters or maybe adding some arbitrary call data.
The unique transaction will have unique hashes which allow us to associate them back to exactly one of our submission strategies.
Once we know which strategy was actually successful we should also add metrics for it.

**Comment by sunce86** [comment]
> The unique transaction will have unique hashes which allow us to associate them back to exactly one of our submission strategies.

I am not sure how this can be done (programmatically)? Do you already have an idea or? 
I was expecting maybe to send the `TransactionStrategy` together with transaction submission status back to driver or something like that...

**Comment by MartinquaXD** [comment]
> Do you already have an idea or?

I already worked on that a bit. My plan was to store some meta data in the `TransactionHandle` like this. 
```rust
pub struct TransactionHandle {
    pub handle: H256,
    pub tx_hash: H256,
    pub submitted_by: String,
}
```
Each submission strategy already knows it's own name so it knows what value to add.
Since we now have the data we need inside the handle we can recover it from the original transaction handles [here](https://github.com/cowprotocol/services/blob/main/crates/solver/src/settlement_submission/submitter.rs#L270-L288)
I believe the only challenge would be to find an elegant way to make each transaction hash unique such that there is always exactly 1 original `TransactionHandle` to recover the meta data from.

**Comment by nlordell** [comment]
> I believe the only challenge would be to find an elegant way to make each transaction hash unique such that there is always exactly 1 original TransactionHandle to recover the meta data from.

We have a few options:
1. Add some random jitter to the `maxFeePerGas` (**NOT** `maxPriorityFeePerGas`). This is essentially free (because you only pay up to the block base gas price from here - so if you could only actually overpay if the base block gas price is just in between what you quoted and the random jitter - which is extremely unlikely if the jitter is a few wei).
2. Append some additional calldata. This gets ignored by the Settlement contract when decoding the calldata and is more "permanent" (i.e. we can determine which solver it was based on the extra bytes we add). The downside is that we pay for this (16 gas per non-zero byte and 4 gas per 0 byte - a very small amount compared to the overall gas usage of a settlement at 200k - 1M).

Personally, I would be slightly inclined to go for 1 because its free. There are arguments to be made for 2, however, such that it would be trivial to get the information about which submitter was used in external tools (such as Dune).

**Comment by MartinquaXD** [comment]
Yeah, those are the options I already mentioned in the issue description.
I think a very easy way to introduce jitter would be to assign each submission strategy a constant tiny `maxFeePerGas` offset and add that to the "original" settlement. (flashbots: 0, eden: 1, custom_nodes: 2 + index of custom node (in case there are multiple which we would like to differentiate))
My concern with "elegance" was more regarding keeping stuff testable (no unseeded randomness) and not offering too many configuration options (I think hardcoding the values is okay).

**Comment by nlordell** [comment]
> Yeah, those are the options I already mentioned in the issue description.

Sorry, just read the last comment and not the whole thread 🙈.

> I think a very easy way to introduce jitter would be to assign each submission strategy a constant tiny maxFeePerGas 

The issue is I think they take estimates at different times, so they could in theory (albeit almost impossibly) collide. We would need something like a `SingleUsePriceEstimator` to our wrap gas price estimating interface with some silly logic like:

```rust
impl GasPriceEstimating for SingleUsePriceEstimator {
    fn estimate_gas(&self) {
        let mut estimate = self.inner.estimate_gas();
        while self.previous_estimate.contains(estimate.maxFeePerGas) {
            estimate.maxFeePerGas += 1;
        }
    }
}
```

We would create one of these for each settlement loop (we don't need to keep track of previous estimates across driver runs).
