### ISSUE TITLE
chore: Remove SellAmount::AfterFee enum

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2589]
### Background
https://github.com/cowprotocol/services/blob/main/crates/model/src/quote.rs#L257-L268

AFAIU the point of this enum is to differentiate between (legacy) market and limit orders quote requests.
Now that we killed legacy market orders, we should also clean this up and remove enum.

I personally find it very hard to understand quotes with this enum, as it is complicated to deduct how the values are propagated throughout the codebase.

**Comment by fleupold** [comment]
I agree that with all orders being limit orders this enum makes less sense (since the fee that is being returned is not guaranteed, so you may end up selling a bit more or less in the end), but I don't think it's worth the effort to remove it. This would require a breaking API change which I think should be held off for a v2 of the API (potentially in combination with a new settlement contract).

**Comment by sunce86** [comment]
We can keep it in API only, while removing from all the internal code (for code clarity).

**Comment by fleupold** [comment]
@sunce86 I saw you started cleaning up some market/limit order stuff. Do you still want to tackle this issue?
