### ISSUE TITLE
feat: Add economic viability check in the driver

### ISSUE THREAD

**Issue by harisang** [cowprotocol/services#2613]
This was requested from a solver team and asks for the following feature that could be enabled with a flag:

When the driver simulates the solution, it checks whether `estimated_cost > network_fees`, and if so, replaces the proposed solution with the empty one.

**Comment by fleupold** [comment]
I wonder if we should use the `gas` field that was recently added for `quotes` here? This would make it very easy to enforce (if estimated gas in the solution is larger than that, drop the solution).

Otherwise, I'm not sure it's clear how a gas amount should be translated into the fee which is charged in sell token? Which values do we assume for sell token price, gas price?

Can we also check how many solver teams are interested in that? It feels a bit like a niche feature, that should have low priority compared to the other issues (most solvers are able to simulation their solutions, and we have tasks to make that easier). Once you can simulate your own solution, why don't you implement this check?

**Comment by harisang** [comment]
> I wonder if we should use the gas field that was recently added for quotes here?

Yeah good point, this should be the fastest way out. Have the gas field used interpreted as a gas limit. Although there is a systematic way of converting fees in sell tokens to ETH, it would mean the driver would need to pull again these prices together with the gas price in order to implement the check.

> Can we also check how many solver teams are interested in that?
I am aware of one team interested in this. So I agree it is a low priority item. If the `simulated_gas >? solver_reported_gas` is an easy thing to do, then we go for that solution, given that we have time to implement this in the first place.
