### ISSUE TITLE
chore: Store surplus capturing jit order owners in solver_competitions table

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#2793]
### Background
The external circuit breaker implementation relies on the solver competitions table to function correctly.
One of the checks is that the score promised by the solver and the score delivered onchain should be the same.
Since cow amm orders can be created just in time we need to store for each auction which jit order owners were considered to be surplus capturing for a given auction.

**Comment by harisang** [comment]
Definitely needed, and i would also argue that it is also the right thing to do so that we can have a complete description of an auction instance.

**Comment by sunce86** [comment]
Do you think we should enforce finished indexing (indexing to the latest known blockchain block) on each autopilot restart, before entering the auction loops? Otherwise, there could be a racing between autopilot and driver, where autopilot is lagging and not all cow amm owners are saved to db while driver could settle those non-existent ones, which would again lead to skipping some cow amms for surplus/score?
