### ISSUE TITLE
Add Block Number At Order Creation To Metadata

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#313]
This issue captures the work for adding a `creation_block` to the order's metadata at the time of order creation.

This can be used to give us an approximation on when the order was created from a block-chain perspective. While we currently already have `creation_timestamp`, which gives us a pretty good idea, adding the block number is simple enough (we should already have access to it with our `CurrentBlockStream`) and opens the door to do better order analysis.

**Comment by nlordell** [comment]
@bh2smith - interested in getting back into some Rust ;)?

**Comment by bh2smith** [comment]
Yea, this is something I would like to do, but I am still trying to determine if this is as valuable info as we originally thought.

Specifically, quotes are cached and sometimes users would get a chached (not yet expired quote) that might correspond to an old block. I am wondering how accurate this info might actually be. Similarly, if a user gets a quote and opens up their wallet to sign an order, but gets distracted and signs later... will the backend reject the order because the quote they are trying to sign is too old?

**Comment by vkgnosis** [comment]
I've been hesitant to add things to the database that the services themselves don't need. We'd be adding this to make analytics easier only. That can be worth it and this is a small change but I did want to bring this up. In the slack thread Ben said he is combining Dune and the Database so one question is if there isn't an alternative way to get an approximation of the current block at some real time instant. Also we should be sure that the block number is useful because it is just "approximate". There is no global correct current block number. It depends on the observer and it can change afterwards due to reorgs.

**Comment by bh2smith** [comment]
We can, of course, match order creation timestamp within some block_number window. However, this also brings us back to the problem of having our system clock misaligned with the miners clock. Again, we will wind up with quote block numbers larger than settlement blocks.

Additionally we might find that querying quotes for blocks found in this manner yield no results on our orderbook quotes because the block number we find could be different than the actual quote. This would then mean two different loss of precisions 
1. search for block based on creation time window
2. search for quote based on block time window...

Overall I would say that its not realistic to attempt to match creation times with block numbers based on EVM/Dune data.

If we are ever going to accurately measure user surplus, we need to be able to determine (with any degree of accuracy) what the user's slippage parameter was at the time they placed the order.

**Comment by nlordell** [comment]
> I've been hesitant to add things to the database that the services themselves don't need.

Hmm. This is a valid point. One argument I typically have for including block number information is that Ethereum is "block-centric" and including what our current view of the blockchain was when the order was created makes sense in that regard. I guess I need to think about this a little more to decide if its really needed.

Another option is to create a secondary table (that may even be populated by a separate binary specific to analytics needs), something like "seen blocks" with timestamp and block number columns.

> Again, we will wind up with quote block numbers larger than settlement blocks.

This can be worked around with something like `min(approx_order_block, settlement_block - 1)` right - and we'd still have a decent approximation of the block number? The question to me is "how important is the accuracy?".

> If we are ever going to measure user surplus, we need to be able to determine (with any degree of accuracy) what the user's slippage parameter was at the time they placed the order.

I'm not sure I understand how block numbers are important for this specifically (especially since we store order quotes by order UID in the database and can compute the slippage that way).

**Comment by bh2smith** [comment]
> especially since we store order quotes by order UID in the database and can compute the slippage that way. 

I was not aware of this at the time I requested the block numbers for the quotes. If orders and quotes can be linked by `order_id` then there is nothing that needs to be done here.

> `min(approx_order_block, settlement_block - 1)`
I do like this suggestion, although it gives rise to an issue we are bound to face eventually when our data aggregation gets more demanding; Specifically,

1. Get orders with creation_timestamps (from orderbook)
2. get block times and numbers from wherever (say between the start and end date of orders fetched).
3. Update orders with this approximation.
4. Get trades from dune and join on orders.

Essentially we will find ourselves injecting results from one source query into our query for the other source.
