### ISSUE TITLE
Investigate "found pools that don't correspond to any known Balancer pool factory "

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#343]
We are currently logging this warning:
```
WARN shared::sources::balancer_v2::pool_fetching: found pools that don't correspond to any known Balancer pool factory total_count=3
unused_pools=
{
0x8df6efec5547e31b0eb7d1291b511ff8a2bf987c: RegisteredPools
    {
        fetched_block_number: 15088180,
        pools: [
            PoolData { pool_type: Stable, id: 0x178e029173417b1f9c8bc16dcec6f697bc32374600000000000000000000025d, address: 0x178e029173417b1f9c8bc16dcec6f697bc323746, factory: 0x8df6efec5547e31b0eb7d1291b511ff8a2bf987c, swap_enabled: true, tokens: [Token { address: 0x586aa273f262909eef8fa02d90ab65f5015e0516, decimals: 18, weight: None }, Token { address: 0x6b175474e89094c44da98b954eedeac495271d0f, decimals: 18, weight: None }, Token { address: 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48, decimals: 6, weight: None }]},
            PoolData { pool_type: Stable, id: 0x2d011adf89f0576c9b722c28269fcb5d50c2d17900020000000000000000024d, address: 0x2d011adf89f0576c9b722c28269fcb5d50c2d179, factory: 0x8df6efec5547e31b0eb7d1291b511ff8a2bf987c, swap_enabled: true, tokens: [Token { address: 0x5c6ee304399dbdb9c8ef030ab642b10820db8f56, decimals: 18, weight: None }, Token { address: 0xf24d8651578a55b0c119b9910759a351a3458895, decimals: 18, weight: None }] },
            PoolData { pool_type: Stable, id: 0x3dd0843a028c86e0b760b1a76929d1c5ef93a2dd000200000000000000000249, address: 0x3dd0843a028c86e0b760b1a76929d1c5ef93a2dd, factory: 0x8df6efec5547e31b0eb7d1291b511ff8a2bf987c, swap_enabled: true, tokens: [Token { address: 0x5c6ee304399dbdb9c8ef030ab642b10820db8f56, decimals: 18, weight: None }, Token { address: 0x616e8bfa43f920657b3497dbf40d6b1a02d4608d, decimals: 18, weight: None }] }]
    }
}
```

This looks weird to me because the pool type is Stable but the factory address is not the one we have in the repository. It seems like someone else created a new StablePoolFactory. This does not match how we model balancer in our code where we expect only one StablePoolFactory.

Found a reference to this here https://github.com/balancer-labs/balancer-subgraph-v2/commit/e23515e4702d557fe58965656a67e388669a22b0.

**Comment by nlordell** [comment]
The code should be setup in a way where you can have multiple factories for similar things (see `WeightedPoolFactory` and `WeighedTwoTokenPoolFactory`). It might be something easy to solve (although, now sure how impactful it will be).

**Comment by markusbkoch** [comment]
@nlordell is right. We may sometimes deploy new factories for pools of the same type. In this case, `0x8df6efec5547e31b0eb7d1291b511ff8a2bf987c` is a [new stable pool factory](https://github.com/balancer-labs/balancer-v2-monorepo/tree/master/pkg/deployments/tasks/20220609-stable-pool-v2) that deprecated [the previous one](https://github.com/balancer-labs/balancer-v2-monorepo/tree/master/pkg/deployments/tasks/deprecated/20210624-stable-pool). 

Note that the previous one can't be "shut down", so people can still deploy pools with it. But due to the known issues we'll disincentivize its use to the extent possible (eg no new pools deployed by the old factory should be expected to be added to the Balancer UI).

**Comment by nlordell** [comment]
@markusbkoch - do you know why the previous one was deprecated and what were the issues?

**Comment by vkgnosis** [comment]
I'm wondering if the math we have implemented for the v1 stable pools still holds for v2. Since you're mentioning the invariant computation which I also see referenced in in our code [here](https://github.com/cowprotocol/services/blob/46dd0cc60cef16886cce88b102c388adca9c39be/crates/shared/src/sources/balancer_v2/swap/stable_math.rs) it probably does not. Also relevant for our Quasimodo solver.

(Not really directed at anyone, just thinking out loud for reference. Also CC @bh2smith because you did most of the balancer implementation and we talked about this issue on Slack. Feel free to ignore the ping since you're not working on the backend atm.)

**Comment by markusbkoch** [comment]
> I'm wondering if the math we have implemented for the v1 stable pools still holds for v2

Good point, we'll look into it and get back to you soon.

**Comment by bh2smith** [comment]
So, we have implemented stable math here: https://github.com/cowprotocol/services/blob/f7e53c3ba626cc71505b18b74e7abeb3df02f831/crates/shared/src/sources/balancer_v2/swap/stable_math.rs#L19-L84

It appears that `calculate_invariant` has been changed (d_p instead of p_d). I will have to look a bit closer and see what (if anything needs to be changed on our side). Do you happen to have any new unit tests that were introduced to demonstrate the difference between the old and the new implementation? This would help determine if anything has actually changed or if its just semantics.

**Comment by EndymionJkb** [comment]
Yes; that was a stale comment (already fixed in repo by #1488. Thanks!

**Comment by bh2smith** [comment]
> Yes; that was a stale comment (already fixed in repo by #1488. Thanks!

So which comment was fixed, could you link to the actual change so I can see? 

Have there been any new unit tests introduced upon making these changes? Is there a specific PR I could look at that shows exactly what changed from one version of the contract to the other? Generally I find that these balancer contract projects change the entire directory structure every time you change a contract. Makes tracking the diff pretty challenging.

**Comment by EndymionJkb** [comment]
There's a whole year between the initial and current StablePool
deployments, so the codebase did change significantly in that time. (In
particular, one big and fairly recent reorganization that touched almost
every file was the introduction of /interfaces to prevent circular
dependencies PR #1285.) It won't be very helpful to directly diff deployed
code over that kind of time range, unless you pull the function of interest
out and compare just that code in isolation.

It's best to look at file changes within recent PRs. PR #1488 (
https://github.com/balancer-labs/balancer-v2-monorepo/pull/1488/files)
simply removed the two lines with misleading comments.

PR #1330 (
https://github.com/balancer-labs/balancer-v2-monorepo/pull/1330/files) was
the one that changed StableMath to extend the convergence range (and
removed the directional rounding)

**Comment by bh2smith** [comment]
Thanks @EndymionJkb - I have made the analogous changes to our implementation of `calculate_invariant`

https://github.com/cowprotocol/services/pull/368

At the moment only one of our unit tests is failing (something that was not expected to converge before, that is converging now) - which aligns with the purpose of the change, to "extend the convergence range".

My only question now is whether we now need to support both implementations (one for all new stable pools and one for all old stable pools) or have the old pools been upgraded to refer to the new implementation?

**Comment by EndymionJkb** [comment]
Yes, I also changed that test. It now says "still converges at extreme
values":
https://github.com/balancer-labs/balancer-v2-monorepo/blob/133359ac8b6f2cf2e19a123d10313fb02f92cb7d/pkg/pool-stable-phantom/test/StableMath.test.ts#L65

When the final stable release comes, there will be only one kind of Stable
pool: the StablePhantomPool (probably renamed to be less spooky), with the
capabilities of regular Stable pools (e.g., multi-token joins/exits) merged
into PhantomStable. There are no further changes to the math.

The V1 stable pool (from '21) is deprecated, and new pools should
use/migrate to the latest, when it's released. The 20220609 regular
StablePool release (V2) was a stopgap until the full Phantom merge is
completed, but has the updated math and all vulnerabilities addressed, so
it is perfectly fine to use, if you don't need the Phantom functionality.
Some new projects deployed using that version of plain Stable, so it should
be supported.

The blockchain is forever, so people might continue using the originally
deployed Stable pools (20210624), but they're officially deprecated. Note
their presence in the deprecated folder in /deployments:
https://github.com/balancer-labs/balancer-v2-monorepo/tree/master/pkg/deployments/tasks/deprecated
.

**Comment by bh2smith** [comment]
This is all fantastic news. It sounds a bit like our back end services will still need to support the possibility that older versions of the pool are being used. Since this is the case, then we would need some way of identifying which stable pool uses what invariant calculation. Is this something we can determine automatically from the pool itself, or something we would have to hardcode in our project? I can imagine something like a boolean flag on the pool's attributes like `uses_deprecated_arithmetic`, just wondering if the pool contract itself has some indication which invariant it is using?

**Comment by bh2smith** [comment]
The PRs related to this issue have been merged and will soon be available in our staging environment.

So, within the next few minutes, we should be able to 

1. place an order involving tokens contained within these pools on https://barn.cowswap.exchange/#/swap?chain=mainnet
2. If one of these pools has deep enough liquidity, we should see that it is filled via one of these pools.


Note that one of those pools involves a BPT (aka LP token) which is not a likely candidate to select as a tradable token. However, we may find that since there exists a pool for it, it does become tradable. I suspect this will not be the case however, since the pool containing this BP token does not also contain one of our "base-tokens" In any case, these pools should now be entered into the ring for competitive prices. I will try and force a trade using one.
