### ISSUE TITLE
Submit fully optimized solution in the settlement competition

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#438]
Right now the driver simulates and ranks all submitted solutions and sends those settlements along with their objective value to the `/solver_competition` endpoint.
Slightly problematic for our data integrity is that we optimize the winning solution afterwards meaning that the winning solution we submit on chain might not be 100% identical to what we stored in the `/solver_competition` endpoint.
The winning solution we log during the driver run might also not be 100% correct.

A simple fix should be to optimize the winning solution first and then compute a new `RatedSettlement` from it. We might even want to store the original and fully optimized solution in the `/solver_competition` endpoint.

**Comment by nlordell** [comment]
> We might even want to store the original and fully optimized solution in the /solver_competition endpoint.

We definitely do. Specifically, solvers are on the hook for producing calldata for interactions that were internalized (prove that the liquidity existed).

**Comment by vkgnosis** [comment]
Is this really an issue? We know what optimizations we perform for the winning settlement after picking it. The solver competition endpoint is supposed to give you information about the competition which is not influenced by our optimization.

In SolverCompetitition we store 

```rust
pub struct SolverSettlement {
    pub solver: String,
    pub objective: Objective,
    pub clearing_prices: BTreeMap<H160, U256>,
    pub orders: Vec<Order>,]
    pub call_data: Vec<u8>,
}
```

The only parts that can change with the final optimization is the call_data and the objective. The call_data is already on chain so this data is available and the objective is a driver internal value that only matters for ordering the solutions which is irrelevant when the winning solution has already been picked.

**Comment by nlordell** [comment]
> objective is a driver internal value that only matters for ordering the solutions which is irrelevant when the winning solution has already been picked.

Since we publicize the objective value and is part of the official settlement competition that includes external solvers, I would argue this should not be considered as an internal-only value.

Actually, in terms of solver competition, I think we need to start storing calldata for non-internalized AMM swaps **and** the final calldata with internalized AMM swaps (and again, move this internalization to the `SingleOrderSolver` level and not a general post-processing step). This will be important to be able to "go back in time" and verify the calldata with internal swaps that external solvers proposed.
