### ISSUE TITLE
[BadToken] Miracle Token

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#62]
The following settlement failed to simulate: https://dashboard.tenderly.co/gp-v2/staging/simulator/289cb4ce-9aef-4099-ac58-8c2fb26f0b9c

because of an invariant in the [Miracle Token](https://etherscan.io/address/0x3b449d25eb3cbad66cf76694a7c4216cfc6b9441) Contract:

```
require(amount < rTotal);
```

amount: 11074246714981099536953
rTotal:     1000000000000000000

I assume the bad token detector did not catch this because we test transferring a fixed amount that happened to be below the `rTotal` value.

This issue would likely be also addressed if #858  was implemented.

> Original issue https://github.com/gnosis/gp-v2-services/issues/870 by @fleupold

**Comment by MartinquaXD** [comment]
We should no longer try to improve the bad token detection since it's a flawed system. Instead we should ditch it entirely and allow placing any order for which we can get a verifiable quote. That way it's enough if one solver is able to trade a given token and we don't have to add more and more edge cases to the automated test.
