### ISSUE TITLE
Surplus Fee Amount Finality

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#771]
We should store a "final" surplus fee value that was used during the order execution. The reason for this is we want to show this fee in the explorer UI.

Additionally, we could open up the discussion of changing the order model that is used for the explorer UI and the one that is used by the auction end point (see #529) as well as the meaning of various fields:
- Should we merge `surplusFee` and `feeAmount` for the API orders? My intuition is _no_ because this represents the signed order fee amount (so if you want to verify a signature from an `api/v1/orders/$orderUid` request, you would need special handling to build the "actual" order that is being used).
- Should we use `executedFeeAmount` for the "final" surplus fee? My intuition is _no_ because this represents what is emitted as part of the smart contract event.

Perhaps we can create an `api/v2/orders/$orderUid` or `api/v1/orders/$orderUid/description` API end point that just returns an order "description" and is closer to what the FE API wants to display?

cc @anxolin.

**Comment by vkgnosis** [comment]
Was thinking about how we should store this. We already have the surplus_fee column in the orders table and if the order has been settled then this is the value that was used.

...That's would I would like to say but it could happen that we settle an order and while that settlement is in progress autopilot updates the surplus_fee, making it inaccurate. Unfortunately that doesn't work. Maybe there is some clever way of getting this to work?

If we can't then we need a new column that works like the order rewards in the sense that is determined by the driver and sent to the db for a settlement. So that would be a new column or new table.

**Comment by nlordell** [comment]
Maybe this should be part of the `order_rewards` table. We can rename it to "order_execution" and add a column for this (so it has the same auction ID <> transaction linking and deals with issues like a settlement reverting or timing out when mining).

I think that in the end you were right and should have added DB access to the `solver` binary (or at least, to the parts that we plan on migrating to the `autopilot` when we get back to working on solver+driver colocation).
