### ISSUE TITLE
Spec-out new HTTP interface for searchers.

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#831]
This issue captures the work to re-specify the HTTP interface between the driver and HTTP solvers (for example Quasimodo and other external solvers).

The current interface developed in an ad-hoc way, and it would be nice to redefine it so:
1. It is more in-line with the design in the driver-solver co-location
2. Clear up some of the "API technical debt" that has accumulated with it

The current API is defined in [`shared::http_solver::model`](https://github.com/cowprotocol/services/blob/main/crates/shared/src/http_solver/model.rs), See also example attached [instance.json](https://github.com/cowprotocol/services/files/10113821/instance.txt).

**Comment by nlordell** [comment]
I think this would be the interface between `protocol` and `driver` (so what we have defined [in this OpenAPI spec](https://github.com/cowprotocol/services/blob/main/crates/driver/openapi.yml)).

For this issue, I was thinking about the `driver` <> `searcher` communication.

**Comment by sunce86** [comment]
One requirement would be to allow searchers to submit more than 1 solution per auction right?

**Comment by nlordell** [comment]
> One requirement would be to allow searchers to submit more than 1 solution per auction right?

No, I think that the Gnosis Solvers will locally chose their best solution - so everyone will submit one solution per auction.

**Comment by vkgnosis** [comment]
We had talked about on Slack in the solvers channel that it could be useful to allow solvers to submit two solutions so that if one randomly becomes unsimulatable the other might still be useful. The idea was positively received.

Not entirely sure how this would look with colocation (does auotpilot need to know about the multiple solutions or can driver handle it). I think we should keep this in mind but not think too hard about it now until we have the rest of the colocation.
