### ISSUE TITLE
Colocation: Figure out details of the autopilot-driver API

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#876]
There have been many comments in https://github.com/cowprotocol/services/pull/874 that should be addressed. Some are for details that have intentionally been left out before like the exact order data and how the signature works and some are for tweaks to the api.

**Comment by sunce86** [comment]
`BlockNumber` is not something that is reliable enough I'd say. It could happen:
1. `Autopilot` asks what is the latest block but it lands on a node lagging 2 blocks behind (which is not that rare right?)
2. Driver starts executing but it's already considered that 2x12s is spent solving.

Although I do agree we should switch to `BlockNumber` instead of seconds, I just wanted to raise the concern.

**Comment by nlordell** [comment]
I think in this case, the external driver should reject solving based on the block being too far in the past.

I actually think this is an argument for using `BlockNumber` everywhere, as it makes it easier for the system to detect is it is lagging based on external sources of truths (the external drivers).
