### ISSUE TITLE
Add Settlement Execution Deadline

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#880]
Once a solver competition winner is chosen, the `autopilot` will make an HTTP request to `/execute` on the winning driver, signaling that the driver should start trying very hard to get its winning settlement transaction on-chain.

I believe it is important for the execution deadline to be in blocks and not seconds, as you can empirically say: "your transaction did or did not get included by this block number". Using time is not as reliable as system time != block timestamps, making it harder to analyze missed deadlines in the past.

The block deadline must be agreed upon (and signed) by the `autopilot` and `driver` to avoid confusion when looking at historical data. In other words, the block deadline should be part of the signed payout at some point during the `autopilot` <> `driver` exchange in a solver competition.

To clarify: the acceptance criteria for this issue is simply to pass the signed deadline to the solver, the rewards accounting is a manual process carried out by the solver team.

**Comment by vkgnosis** [comment]
A deadline for /execute is only meaningful if it has an effect. Will the transaction submission algorithm change based on the deadline? What is the punishment for not adhering to the deadline?

(For /solve the answer is that a driver won't be considered in the competition if it takes too long.)

**Comment by MartinquaXD** [comment]
> The block deadline must be agreed upon (and signed) by the autopilot and driver...

Is the deadline allowed to be dynamic or is it only allowed to be changed by a CIP? I'm asking because if the deadline is too soon and solvers don't feel like they could satisfy the deadline, they should probably be allowed to opt out of the competition to avoid getting slashed. With that in mind it would make sense to make this deadline already part of the `/solve` request to avoid drawing a winner that later refuses to submit its solution.

Also then it could make sense to add a CLI switch to the driver that configures what kind of execution deadline its willing to accept, right? Although the willingness to execute the solution in time should probably be determined dynamically based on network congestion.

**Comment by nlordell** [comment]
To be clear, this is the deadline for getting a transaction on-chain. To me there are two deadlines:
- A "time" deadline for `/solve` to complete
- A block deadline for, once a `driver`+`searcher` accepts an `/execute` request, for that settlement to arrive on-chain.

> With that in mind it would make sense to make this deadline already part of the /solve request to avoid drawing a winner that later refuses to submit its solution.

Yes, although in theory they can respond to `/execute` with a "won't execute" response (which we allow) and then we would fall-over to the runner up winner, so it won't affect the protocol but might be nice from the solver perspective. I don't feel strongly either way.

**Comment by fleupold** [comment]
We do have a `max_confirm_time` config in the driver's submission config.
