### ISSUE TITLE
`/execute` endpoint for `driver`

### ISSUE THREAD

**Issue by sistemd** [cowprotocol/services#896]
The purpose of `/execute` is to publish the settlement transaction on the blockchain. It needs to encode the solution into its onchain form. The reference implementation of this process can be found in the [`SettlementEncoder`](https://github.com/cowprotocol/services/blob/6988d10081b57c8a12c1ac0adff6bac13e93626c/crates/solver/src/settlement/settlement_encoder.rs#L32). The only additional detail concerning the `driver` is that the solution ID should be encoded as part of `calldata`. More details about this below.

The `driver` needs to support multiple submission strategies:
- [ ] Using the public mempool.
- [ ] Flashbots.
- [ ] Gelato.

Reference implementations of each strategy can be found today as implementations of the [`SettlementSubmitting`](https://github.com/cowprotocol/services/blob/b40e4883e719a6f235b94a26ac9efb2cbb8af594/crates/solver/src/settlement_submission/submitter.rs#L101) trait. The `driver` should be configured with CLI flags to determine which strategy should be used.

#### Input

TODO

#### Output

TODO

**Comment by vkgnosis** [comment]
Continuing the discussion from https://github.com/cowprotocol/services/issues/895#issuecomment-1335375205 about the ID. If there is no security reason for doing the CSPRNG approach then I'd like to re-use the auction id. It's simpler and it intuitively feels more proper.

I'm not completely certain that there is no security issue yet. Still thinking about it.

**Comment by MartinquaXD** [comment]
I believe simply using the auction id to associate the solution with a solver has a slight problem. Staging and prod have different auction id counters but use the same settlement contract, right? That would mean eventually we would end up with 2 settlements that have the same id associated with them (when the prod auction id catches up to the current staging id). Technically we would be able to know which settlement belonged to staging and which to prod based on the submission timing and solver address (so far solvers always had different addresses across staging and prod) but it seems cleaner to me to simply use random ids to avoid collisions.

**Comment by vkgnosis** [comment]
Auction id is what identifies auctions. It is natural to use it here because our goal is to identify an auction. I don't think it's more likely that we overlook something there versus another approach of picking it.

With a random id there is also a chance of conflict (I didn't do the math for how many auctions). With the auction id the conflict is only between staging and prod which we have a solution with the reasonable (?) assumption that solver addresses are not reused between staging and prod. With a random id there can be conflicts in the same environment which is harder to handle.

**Comment by nlordell** [comment]
Auction IDs are already not unique and don't have unique guarantees. For example, if I run a local Görli protocol setup and actually submit on-chain orders, there is high chance of colliding IDs. Also, they aren't unique across deployments (as @MartinquaXD) so I would avoid using them (unless we turn them into "auction UIDs" that are coll

> With a random id there is also a chance of conflict

I think if with enough high-quality entropy (32 bytes from `/dev/urandom` should be cryptographically strong enough for this), this should be a non-issue.

**Comment by MartinquaXD** [comment]
> With a random id there is also a chance of conflict (I didn't do the math for how many auctions).

I think we can "buy" ourselves the chance we need/want by making sure the additional data has enough entropy to avoid collisions. The number of additional bytes doesn't affect the competition and is very cheap gas-wise. Overall I think this is not a problem for the secret key.

I guess the issue comes down to how we deal with settlements where the additional data (secret key or auction id) is not enough to associate it to an auction. I believe dealing with ambiguity there will be quite annoying (e.g. solver rewards payout). With a secret key it could still happen that some bad actor takes the secret key from another auction to mess with us but at least with the secret key we would only have to deal with that in the case of bad actors. If we take the auction id everybody could play by the rules and we still end up with collisions.

Also the plan to add additional data to the `call_data` to associate solutions hinges on it being efficient enough for the solver rewards payout. If that it is not possible it might make sense to think about another solution again.

**Comment by nlordell** [comment]
> The number of additional bytes doesn't affect the competition and is very cheap gas-wise

Its 20 gas per byte. Seeing as how solutions are around the 200,000 gas mark (for a single trade), that is 0.01% of the overall cost per byte.
