### ISSUE TITLE
Separate price quote and solve requests

### ISSUE THREAD

**Issue by harisang** [cowprotocol/services#974]
It would be convenient to not mix the two requests and have separate calls,  `/quote` and a `/solve `

**Comment by vkgnosis** [comment]
Could you add some motivation to the issue? Has probably been talked about elsewhere but reading just the issue it's not obvious why it matters.

**Comment by poolpitako** [comment]
@vkgnosis We would like to route quote orders to a different set of instances than the ones doing solve.

**Comment by nlordell** [comment]
We should be able to do this today already, but specifying different configurations for price estimation and for solving.

Concretely, you should already be able to configure:
- https://my.solver.url/auction/solve
- https://my.solver.url/prices/solve

You could even differentiate at a subdomain level:
- https://auction.my.solver.url/solve
- https://prices.my.solver.url/solve

And then we would specify different base URLs in `autopilot` and `orderbook` than we do in `solver` binaries and achieve this separation without requiring all external solvers to implement a separate URL.

Personally, I would solve it this way instead of adding additional code and API complexity.

**Comment by fleupold** [comment]
This is implemented.
